"""migrate 1

Revision ID: 00fb735d5089
Revises: 
Create Date: 2017-11-18 19:55:52.620084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00fb735d5089'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pinginfos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.SmallInteger(), nullable=True),
    sa.Column('category', sa.SmallInteger(), nullable=True),
    sa.Column('jobTitle', sa.String(length=100), nullable=True),
    sa.Column('pingType', sa.SmallInteger(), nullable=True),
    sa.Column('time', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('link', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8'
    )
    op.create_table('requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=200), nullable=True),
    sa.Column('pinginfo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pinginfo_id'], ['pinginfos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requirements')
    op.drop_table('pinginfos')
    # ### end Alembic commands ###
